services:

  test-app:
    build: .
    restart: "no"
    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testdb
      SPRING_DATASOURCE_USERNAME: fusion
      SPRING_DATASOURCE_PASSWORD: fusion
    depends_on:
      - postgres

  postgres:
    image: postgres:17.1
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/testdb
    environment:
      POSTGRES_USER: fusion
      POSTGRES_PASSWORD: fusion
      POSTGRES_DB: testdb
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

volumes:
  postgres_data: